---
apiVersion: v1
kind: Namespace
metadata:
  name: exo1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exo1-deploy
  namespace: exo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exo1
  template:
    metadata:
      labels:
        app: exo1
    spec:
      containers:
      - name: exo1
        image: opusidea/capge-k8s-exo1:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: exo1-svc
  namespace: exo1
spec:
  type: NodePort
  selector:
    app: exo1
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32700
    protocol: TCP