---
apiVersion: v1
kind: Pod
metadata:
  namespace: simpleweb
  name: redis-pod
  labels:
    app: redis

spec:
  containers:
  - name: redis-container
    image: redis:6.0-alpine
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "256Mi"
        cpu: "750m"

---
apiVersion: v1
kind: Service
metadata:
  namespace: simpleweb
  name: redis # le nom donné au service utilisé en résolution DNS !!!

spec:
  type: ClusterIP # valeur par défaut
  selector:
    app: redis
  ports:
  - targetPort: 6379
    port: 6379
    protocol: TCP