---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb-deploy
  namespace: simpleweb

spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleweb
  template:
    metadata:
      labels:
        app: simpleweb
    spec:
      containers:
      - name: simpleweb-container
        image: opusidea/capge-simpleweb:2.0.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"