---
apiVersion: v1
kind: Service
metadata:
  name: simpleweb-svc
  namespace: simpleweb

spec:
  type: NodePort
  selector: 
    app: simpleweb
  ports:
  - port: 3000
    targetPort: 3000 # port écouté le pod ciblé
    nodePort: 32600 # port pour requête depuis l'extérieur du cluster
    protocol: TCP
