---
apiVersion: v1
kind: Namespace
metadata:
  name: exo2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exo2-deploy
  namespace: exo2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exo2
  template:
    metadata:
      labels:
        app: exo2
    spec:
      containers:
      - name: exo2
        image: opusidea/capge-k8s-exo2:1.0.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: exo2-svc
  namespace: exo2
spec:
  type: NodePort
  selector:
    app: exo2
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32701
    protocol: TCP