---
version: "3"
services:

  redis:
    image: redis:5.0-alpine
    volumes:
    - redis_data:/data

  simpleweb:
    #image: capge/simpleweb:1.0.2
    build: .
    image: capge/simpleweb
    ports:
    - 3000:3000
    depends_on:
    - redis
    restart: always
    volumes:
    - "./public:/app/public"

volumes:
  redis_data: {}
