---
# équivalent de la commande ad-hoc: ansible -m ping slave1
- name: Playbook ping
  hosts: slaves
  gather_facts: no

  tasks:
  - name: ping 1
    ping: {}
  
  - name: ping 2
    ping: data=pang
  
  - name: ping 3
    ping:
      data: pung

...