---
version: '3'
services:
  simpleweb:
    image: opusidea/capge-simpleweb:latest
    ports:
    - 3000:3000
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          memory: 128MB