---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      target: nginx

  template:
    metadata:
      labels:
        target: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.20-alpine
        ports:
        - containerPort: 80