---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service

spec:
  type: NodePort
  selector: 
    target: nginx
  ports:
  - port: 80
    targetPort: 80 # port écouté le pod ciblé (nginx)
    nodePort: 32500
    protocol: TCP
